newmips:
  image: novanit/newmips
  labels:
    io.rancher.sidekicks: seed
database:
  image: percona
  environment:
    MYSQL_DATABASE: ${mysql_db}
    MYSQL_USER: ${mysql_user}
    MYSQL_PASSWORD: ${mysql_password}
  link: newmips:db
  volumes_from:
    - seed
seed:
  image: novanit/newmips-db-seed
  labels:
    io.rancher.container.start_once: 'true'

