newmips:
  image: novanit/newmips
  labels:
    io.rancher.sidekicks: seed
  links: 
    - database:db
  ports:
    - 1337:1337
database:
  image: percona
  environment:
    MYSQL_DATABASE: ${mysql_database}
    MYSQL_USER: ${mysql_user}
    MYSQL_PASSWORD: ${mysql_password}
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
  volumes_from:
    - seed
seed:
  image: novanit/newmips-db-seed
  labels:
    io.rancher.container.start_once: 'true'

