percona-seed:
  image: newmips/percona
  labels: 
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: traefik_lb=true
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  log_opt: {}
