.catalog:
  name: Newmips
  version: "v0.1"
  description: "Newmips Application"
  uuid: newmips-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: mysql_database
      description: "Database Name"
      label: "Mysql Database"
      required: true
      default: "newmips"
      type: "string"
    - variable: mysql_user
      description: "mysql user"
      label: "Mysql User"
      required: true
      default: "newmips"
      type: "string"
    - variable: mysql_password
      description: "mysql password"
      label: "Mysql Password"
      required: true
      default: "newmips"
      type: "string"
    - variable: mysql_root_password
      description: "mysql root password"
      label: "Mysql Root Password"
      required: true
      default: "p@ssw0rd"
      type: "string"